TokTok/dockerfiles

.travis.yml

This doesn't do much - just checks that building the makefiles and
dockerfiles works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/3)

Add travis config.

---

.travis.yml
Makefile
Makefile.pm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/4)

Make `find` invocation osx-compatible.

---

Makefile.pm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/13)

Stop using deprecated (and now removed) "find -perm +...".

---

.gitmodules
.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/19)

Add docker-buildfarm submodule to dockerfiles repo.

---

Makefile
ghc-android/configure
ghc-android/src/Dockerfile.in
ghc-android/src/user-scripts/README
ghc-android/src/user-scripts/build-ghc-cross-compiler.sh
ghc-android/src/user-scripts/build-nettle.sh
ghc-android/src/user-scripts/set-env-android.sh

This is needed for Android to run binaries. All executables must be PIE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/26)

Build all code with `-fPIC`.

---

.circleci/config.yml
.gitmodules
buildfarm/Makefile
buildfarm/base/Dockerfile
buildfarm/builder/Dockerfile
buildfarm/server/Dockerfile
buildfarm/server/entrypoint.sh
buildfarm/server/logging.properties
buildfarm/server/server.config
buildfarm/test/.bazelrc
buildfarm/test/BUILD.bazel
buildfarm/test/WORKSPACE
buildfarm/test/integration_test
buildfarm/worker/Dockerfile
buildfarm/worker/entrypoint.sh
buildfarm/worker/logging.properties
buildfarm/worker/worker.config
heroku.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/29)

Add bazel buildfarm dockerfiles.

---

buildfarm/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/30)

Fix buildfarm makefile.

---

.circleci/build-image
.circleci/config.yml
Makefile.pm
buildfarm/base/Dockerfile
buildfarm/builder/Dockerfile
buildfarm/server/Dockerfile
buildfarm/worker/Dockerfile
ghc-android/src/Dockerfile.in
ghc/src/Dockerfile.in
ghc/src/root-scripts/activate-src-debs.sh
ghc/src/root-scripts/create-androidbuilder-user.sh
ghc/src/root-scripts/install-apt-dependencies.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/34)

Fix some docker lint warnings (hadolint).

---

.github/CODEOWNERS
.github/settings.yml
buildfarm/test/.bazelrc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/35)

Add CODEOWNERS and settings.yml files.

---

.github/settings.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/36)

Fix typo: Codefactor -> CodeFactor

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/39)

Fix circleci config syntax error.

---

.travis.yml
ghc-android/src/Dockerfile.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/45)

fix: Fix "cat readme" at the end of ghc-android builds.

---

buildfarm/Makefile
buildfarm/base/Dockerfile
buildfarm/server/server.config
buildfarm/test/.bazelrc
buildfarm/test/WORKSPACE
buildfarm/test/integration_test
buildfarm/worker/Dockerfile
buildfarm/worker/entrypoint.sh
buildfarm/worker/worker.config
built/Makefile
kythe/webui/Dockerfile

They needed new bazel versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/48)

chore: Fix buildfarm and kythe docker images.

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/50)

chore: Correct ghc version in circle ci build.

---

kythe/buildenv/Dockerfile
kythe/release/Dockerfile.scratch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/52)

chore: Upgrade to bazel 4.2.2.

---

freebsd/Dockerfile
freebsd/Makefile
freebsd/final/Dockerfile
freebsd/final/cmake-freebsd-stage2
freebsd/src/cmake-freebsd-env.sh
freebsd/src/download-freebsd
freebsd/src/setup-vm
freebsd/src/setup-vm.expect

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/53)

feat: Add FreeBSD builder image for c-toxcore CI builds.

---

.circleci/config.yml
compcert/Dockerfile
kythe/buildenv/Dockerfile

Also added libomp5 to the Kythe buildenv. c-toxcore/other/fun/cracker.c
needs that now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/58)

feat: Add CompCert docker image.

---

kythe/webui/Dockerfile

It was missing python3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/59)

fix: Fix kythe webui build.

---

.circleci/config.yml

Apparently circleci's git client has just broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/60)

fix: Install ssh and git in alpine builder images.

---

.circleci/config.yml
.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/61)

chore: Move FreeBSD image build from circleci to github actions.

---

.github/workflows/docker.yml
buildfarm/.gitignore
buildfarm/Makefile
buildfarm/builder/Dockerfile
buildfarm/test/.bazelrc
buildfarm/test/.gitignore
buildfarm/test/WORKSPACE
freebsd/src/download-freebsd
freebsd/src/setup-vm.expect

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/62)

chore: Disable wget spam in freebsd build.

---

buildfarm/builder/Dockerfile

It may be needed for rule execution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/64)

chore: Add python to the builder image.

---

.circleci/config.yml
freebsd/Dockerfile
freebsd/Makefile
freebsd/src/cmake-freebsd-run.sh
freebsd/src/download-freebsd
freebsd/src/setup-vm
freebsd/src/setup-vm.expect
kythe/buildenv/Dockerfile
kythe/buildenv/build_index.sh

Also attempt to fix the FreeBSD image using public key authentication.
It's not working yet, but neither does what we had before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/66)

fix: Disable layering check in Kythe index build.

---

buildfarm/bazel/Dockerfile
buildfarm/test/BUILD.bazel
buildfarm/test/testprogxx.cc

These rarely if ever change, so we can save some time in the toktok-stack
rebuilds on GitHub actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/68)

chore: Add all toktok-stack system dependencies to the bazel image.

---

buildfarm/bazel/Dockerfile

This will happen again later, so this is just a waste.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/71)

chore: Don't download bazel in the bazel image.

---

ghc-android/src/Dockerfile.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/74)

fix: We no longer need to patch gsasl.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/75)

chore: Disable freebsd build for now.

---

buildfarm/builder/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/77)

chore: Upgrade builder image to ubuntu 20.04.

---

.circleci/config.yml
buildfarm/toolchain/Dockerfile
buildfarm/toolchain/prepare_toolchain.sh

This contains the /src/toolchain directory used by toktok-stack builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/78)

chore: Add toolchain docker image.

---

.github/workflows/docker.yml
flutter/web/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/80)

feat: Add flutter-web base image.

---

.github/workflows/docker.yml

buildx does that for us.
Also removed buildx from ghc build, since we don't use it there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/81)

chore: Remove unused checkouts.

---

buildfarm/builder/Dockerfile
infer/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/82)

cleanup: Remove need for pipefail.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/83)

fix: Fix build context passing in docker buildx.

---

.github/workflows/docker.yml

We need to run code outside the default context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/84)

fix: Checkout code in toolchain build.

---

.github/workflows/docker.yml

This is much faster in the common case of no changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/85)

perf: Use docker buildx for ghc builds.

---

compcert/Dockerfile
infer/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/86)

chore: Add msgpack to infer/compcert images.

---

.github/workflows/docker.yml
freebsd/src/cmake-freebsd-run.sh
freebsd/src/setup-vm
freebsd/src/setup-vm.expect

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/87)

chore: Add msgpack to freebsd image.

---

haskell/Dockerfile
haskell/stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/93)

chore: Install our haskell packages from git, not stack.

---

haskell/Dockerfile
haskell/stack.yaml

Base image is build in dockerfiles, then the submodules are built in
toktok-stack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/97)

chore: Split haskell image.

---

haskell/Dockerfile

GitHub actions mount an external home over our own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/98)

chore: Move STACK_ROOT out of HOME.

---

haskell/Dockerfile

This avoids a huge amount of building in the toktok-stack haskell build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/99)

perf: Pre-build toktok-stack haskell dependencies.

---

.github/workflows/docker.yml
buildfarm/cache/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/100)

feat: Add bazel-cache docker image.

---

.github/workflows/docker.yml
nacl/Dockerfile
nacl/install-nacl.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/101)

feat: Add toxchat/nacl image to speed up the nacl build in c-toxcore.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/102)

chore: Upgrade docker actions from v1 to v2.

---

.github/workflows/docker.yml
buildfarm/toolchain/prepare_toolchain.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/104)

chore: Add a toolchain build for bazel 6.3.2.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/106)

chore: Upgrade build-push-action from v2 to v4.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/107)

chore: Update actions/checkout from v2 to v3.

---

kythe/webui/Dockerfile

This is the latest tag that still has the web ui in it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/108)

fix: Use kythe 0.0.60 for the web ui.

---

flutter/web/Dockerfile

Also: clone with 1000 commits, because we need to know the latest tag so flutter can check the release version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/114)

cleanup: Run flutter as non-root in flutter-web container.

---

ghc-android/src/Dockerfile.in
ghc-android/src/patches/gnutls.patch
ghc-android/src/user-scripts/build-gnutls30.sh
ghc-android/src/user-scripts/build-libidn.sh
ghc-android/src/user-scripts/build-libxml2.sh
ghc-android/src/user-scripts/download-ndk.sh
ghc-android/src/user-scripts/install-ndk.sh
ghc-android/src/user-scripts/set-env-android.sh
ghc/src/Dockerfile.in
ghc/src/root-scripts/install-apt-dependencies.sh
haskell/Dockerfile
haskell/stack.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/115)

chore: Upgrade ghc base image to ubuntu 22.04.

---

ghc-android/src/user-scripts/build-gmp.sh

See https://github.com/actions/runner-images/issues/7901
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/117)

fix: Download gmp archive from gnu.org.

---

haskell/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/118)

chore: Fix cirrus-ci haskell build.

---

.github/workflows/docker.yml
frama-c/Dockerfile
frama-c/linux/netdevice.h

Used for sound static analysis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/120)

feat: Add frama-c image.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/122)

refactor: Build the toxchat/builder image on nix.

---

buildfarm/bazel/Dockerfile

Ubuntu's glibc conflicts with nix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/125)

fix: Use alpine image instead of ubuntu for builder.

---

buildfarm/bazel/Dockerfile

Needed for ssh login.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/126)

fix: Give builder a "*" password so it's not locked.

---

.github/workflows/docker.yml

Nix builds are working now, so development here can stop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/128)

cleanup: Re-enable some of the docker builds.

---

.github/workflows/docker.yml
buildfarm/bazel/flake.lock
buildfarm/bazel/flake.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/129)

cleanup: Re-enable ghc image builds.

---

.github/workflows/docker.yml
buildfarm/bazel/Dockerfile
buildfarm/bazel/arion-compose.nix
buildfarm/test/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/138)

fix: Add java to `$PATH` in bazel base image.

---

buildfarm/default.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/143)

fix: Add jdk to remote executor worker.

---

buildfarm/worker.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/144)

fix: Give buildfarm-worker enough capabilities to do sandboxing.

---

.circleci/build-image
.circleci/config.yml
.circleci/wait-image
.github/workflows/docker.yml
infer/Dockerfile

The infer team doesn't do releases, it seems. We should use newer versions, and maybe they will have some of the false positives fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/147)

refactor: Build infer from source.

---

.github/workflows/docker.yml
bazel/build.sh
doxygen/Dockerfile

We build from source, because we want clang parsing support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/148)

feat: Add doxygen image.

---

.github/workflows/docker.yml
pkgsrc/Dockerfile

Running Alpine Linux. This can then be used to build things that depend on toxcore, as well as toxcore itself (with some modifications of the pkgsrc Makefile).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/149)

feat: Add pkgsrc docker image with toxcore in it.

---

.github/workflows/docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/150)

chore: Update github actions.

---

bazel/arion-compose.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/155)

perf: Install jdk11_headless for 500MB less storage used.

---

bazel/Dockerfile
bazel/arion-compose.nix
bazel/arion-pkgs.nix

Something weird happens to clang in 24.05. Downgrading while I investigate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/156)

chore: Downgrade back to nixos 23.11 for now.

---

bazel/Dockerfile

This makes it easier to use it in downstream image builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/157)

chore: Put nixos version into an environment variable.

---

buildfarm/default.nix
buildfarm/server.Dockerfile
buildfarm/worker.Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/160)

chore: Update buildfarm from 2.8.0 to 2.12.0.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.alpine

qTox builds need it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/163)

fix: Install bash into the alpine container.

---

qtox/docker/Dockerfile.debian
qtox/docker/Dockerfile.fedora
qtox/docker/Dockerfile.ubuntu-lts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/164)

chore: Add ninja to qtox build images.

---

qtox/docker/Dockerfile.alpine

Needed for coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/165)

chore: Add compiler-rt to alpine build.

---

qtox/build_vpx.sh

Error was:
```
Unknown option "".
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/166)

fix: Fix the macos distributable build.

---

qtox/build_ffmpeg.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/168)

fix: Avoid empty parameters to configure in ffmpeg.

---

qtox/docker/Dockerfile.alpine
qtox/docker/Dockerfile.fedora
qtox/docker/Dockerfile.ubuntu-lts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/169)

chore: Add libnotify to deps in some qtox docker images.

---

qtox/build_ffmpeg.sh
qtox/build_libexif.sh
qtox/build_openal.sh
qtox/build_openssl.sh
qtox/build_opus.sh
qtox/build_qrencode.sh
qtox/build_sodium.sh
qtox/build_sqlcipher.sh
qtox/build_toxcore.sh
qtox/build_utils.sh
qtox/build_vpx.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/171)

chore: Add support for macos on different architectures.

---

qtox/docker/Dockerfile.android-builder

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/172)

fix: Build openssl as static library for Android.

---

qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.windows-builder

Also make sure COPY'd files in the windows image are readable by non-root builder image users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/173)

chore: Support Android 7 (API 24).

---

bazel/Dockerfile
bazel/arion-compose.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/175)

chore: Update to jdk17 in the docker base image.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.android-builder

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/177)

chore: Add armeabi-v7a builder image for qTox.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.host-qt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/178)

chore: Add support for Android 7 in qTox.

---

.github/workflows/docker.yml
.restyled.yaml
qtox/build_qt_linux.sh
qtox/build_static_qtox.sh
qtox/clang-pc-fixer
qtox/docker/Dockerfile.alpine-static
qtox/toolchain/linux-static-toolchain.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/182)

feat: Add builder image for fully static qtox.

---

.github/workflows/docker.yml
qtox/clang-pc-fixer
qtox/docker/Dockerfile.alpine-static
qtox/toolchain/linux-static-toolchain.cmake

Now we can use dbus and some other stuff like libinput.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/183)

cleanup: Don't use cross compilation for static Qt.

---

qtox/docker/Dockerfile.ubuntu-lts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/189)

fix: Add missing deps in ubuntu-lts image.

---

qtox/build_qt_macos.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/187)

feat: Add macOS Qt builder script.

---

qtox/build_ffmpeg.sh
qtox/build_libexif.sh
qtox/build_openal.sh
qtox/build_openssl.sh
qtox/build_opus.sh
qtox/build_qrencode.sh
qtox/build_qt_macos.sh
qtox/build_sodium.sh
qtox/build_sqlcipher.sh
qtox/build_toxcore.sh
qtox/build_utils.sh
qtox/build_vpx.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/185)

chore: Add option to build some qtox deps as static lib.

---

qtox/build_qt_macos.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/190)

fix: Correct cmake root path in qt macos build script.

---

qtox/docker/Dockerfile.flatpak-builder

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/197)

chore: Add ccache to flatpak builder.

---

qtox/docker/Dockerfile.alpine

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/201)

docs: Add comment to explain why we use old toxcore.

---

qtox/docker/Dockerfile.flatpak-builder

6.8 has weird errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/200)

chore: Downgrade to flatpak kde platform 6.7 again.

---

qtox/docker/Dockerfile.flatpak-builder

Apparently it needs both Sdk and Platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/202)

chore: Also install kde platform into flatpak image.

---

qtox/clang-pc-fixer

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/204)

fix: Fix qtox static linux build (for real now).

---

bazel/Dockerfile
bazel/arion-compose.nix
bazel/arion-pkgs.nix
bazel/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/206)

chore: update nix to 24.11

---

bazel/Dockerfile
bazel/arion-compose.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/207)

chore: dhcp networking

---

bazel/arion-compose.nix

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/208)

chore: Upgrade to bazel 7.

---

qtox/docker/Dockerfile.alpine

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/209)

chore: add alsa pkgs to alpine for appimage

---

qtox/build_extra_cmake_modules.sh
qtox/build_ffmpeg.sh
qtox/build_gdb_windows.sh
qtox/build_glfw.sh
qtox/build_gmp_windows.sh
qtox/build_libexif.sh
qtox/build_libexpat_windows.sh
qtox/build_mingw_ldd_windows.sh
qtox/build_mpfr_windows.sh
qtox/build_nsisshellexecasuser_windows.sh
qtox/build_openal.sh
qtox/build_openssl.sh
qtox/build_opus.sh
qtox/build_qrencode.sh
qtox/build_qt_macos.sh
qtox/build_qt_windows.sh
qtox/build_sodium.sh
qtox/build_sonnet.sh
qtox/build_sqlcipher.sh
qtox/build_static_qtox.sh
qtox/build_toxcore.sh
qtox/build_toxcore_linux.sh
qtox/build_utils.sh
qtox/build_vpx.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/210)

chore: Make sure all dependencies are built with optimisation flags.

---

qtox/docker/Dockerfile.host-qt

We don't need a system Qt installation for this to build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/211)

cleanup: Speed up host-qt build.

---

qtox/build_qt_macos.sh

This affects macOS builds only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/215)

cleanup: Slightly nicer log messages by reducing file path length.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.alpine-appimage

Also reverts changes done in https://github.com/TokTok/dockerfiles/pull/209 , since they are no longer needed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/214)

feat: add alpine based docker file for appimage

---

qtox/build_sonnet.sh

It brings an incompatible hunspell with it, so we have to be explicit about where we want to find ours.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/216)

chore: Fixes for macOS SDK 15.2.

---

qtox/clang-pc-fixer
qtox/docker/Dockerfile.alpine-static

Without backends, there's no sound in qtox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/218)

chore: Add backends to openal-soft so we can have sound.

---

qtox/docker/Dockerfile.alpine-static
qtox/pkg-config-static

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/219)

fix: Build ffmpeg with xcb support for desktop capture.

---

qtox/build_kimageformats.sh
qtox/download/download_extra_cmake_modules.sh
qtox/download/download_ffmpeg.sh
qtox/download/download_hunspell.sh
qtox/download/download_kimageformats.sh
qtox/download/download_libexif.sh
qtox/download/download_libexpat.sh
qtox/download/download_sodium.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/222)

chore: Add kimageformats build (for qoi support).

---

qtox/build_sonnet.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/226)

fix: Link against nsspellchecker on macos-arm64.

---

qtox/docker/Dockerfile.alpine-appimage

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/230)

cleanup: Be selective about image formats in appimage as well.

---

qtox/build_libunwind.sh
qtox/build_libunwind_macos.sh
qtox/build_utils.sh
qtox/download/download_libunwind.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/234)

chore: Add libunwind build file for linux.

---

qtox/build_utils.sh

We need this for std::filesystem::path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/235)

chore: Increase minimum macOS version to 10.15.

---

qtox/build_qtbase_macos.sh

This probably doesn't work, but we'll try.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/236)

chore: Build Qt for macOS 10.15.

---

qtox/build_opus.sh
qtox/build_sodium.sh
qtox/build_utils.sh
qtox/build_vpx.sh

Including simulator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/239)

chore: Add support for more iOS architectures.

---

qtox/build_qtbase_wasm.sh
qtox/build_qtbase_windows.sh
qtox/build_sqlcipher.sh
qtox/build_utils.sh
qtox/docker/Dockerfile.alpine
qtox/docker/Dockerfile.alpine-appimage
qtox/docker/Dockerfile.alpine-static
qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.host-qt
qtox/docker/Dockerfile.wasm-builder

This is to align with Netlify so we can potentially reuse stuff from here in builds there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/243)

refactor: Use /opt/buildhome as prefix for qTox image contents.

---

flutter-web/Dockerfile

Also add clang so we can do ffigen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/245)

chore: Upgrade dependencies in flutter-web.

---

flutter-web/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/247)

chore: Pin the flutter version in the flutter-web image.

---

docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/249)

chore: Add docker-compose file matching the qtox images.

---

.github/workflows/docker.yml
qtox/deps/Brewfile-static
qtox/deps/local_install_deps.sh
qtox/deps/qt.depfile
qtox/download/common.sh

So we don't need to do it in qTox and debugtox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/250)

chore: Add macOS deps build upload.

---

qtox/deps/download_qt.sh
qtox/deps/local_install_deps.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/251)

fix: Correctly determine the script dir.

---

qtox/build_sonnet.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/252)

fix: Fix sonnet static build on macos.

---

qtox/docker/Dockerfile.android-builder

By properly deleting the downloaded sources after building.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/254)

perf: Reduce size of android builder image.

---

qtox/deps/local_install_deps.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/255)

fix: Don't error when no dependencies are installed.

---

.github/workflows/draft.yml
.reviewable/completion.js
.reviewable/settings.yaml
flutter-web/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/256)

chore: Update to flutter 3.29.0.

---

.github/workflows/draft.yml
.reviewable/completion.js
.reviewable/settings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/257)

chore: Add reviewable config; rename release to draft workflow.

---

.github/workflows/docker.yml

It needs to be "toktok", i.e. the organisation name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/260)

chore: Fix ghcr namespace.

---

bazel/Dockerfile
bazel/arion-compose.nix
bazel/build.sh
buildfarm/compose.yml
buildfarm/test/integration_test
docker-compose.yml
kythe/Makefile
kythe/buildenv/Dockerfile
kythe/serving/Dockerfile
kythe/tables/Dockerfile
qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.wasm-builder
qtox/docker/Dockerfile.windows-builder

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/262)

chore: Use ghcr images in all builds.

---

qtox/build_qtbase_linux.sh
qtox/deps/local_install_deps.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/263)

fix: Add sanitizer support to qtbase build on linux.
