TokTok/dockerfiles

Makefile.pm

`keys` on hash references is experimental in 5.20.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/5)

Improve portability to older perl versions.

---

ghc-android/src/user-scripts/build-nettle.sh

Apparently the symbol it's looking for isn't in gmp 6.1.1, making it
think that the version is older than 5.0. Wonderful!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/7)

Patch nettle configure script to look for a different symbol.

---

ghc-android/src/user-scripts/set-env-android.sh

This way, we can import set-env-android.sh from user scripts running
outside of the ghc-build directory (e.g. the work directory).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/28)

Correctly compute the path of set-env.sh in set-env-android.sh.

---

buildfarm/Makefile

Having them is nice, but it causes Circle CI to rebuild buildfarm-base
when building -worker and -server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/31)

Remove dependencies from buildfarm/Makefile.

---

.circleci/build-image
.circleci/config.yml

This should speed up GHC image builds so much that it's essentially free
to run them on every push, so this PR re-enables those builds.
See https://semaphoreci.com/docs/docker/docker-layer-caching.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/32)

Use docker layer caching to speed up builds.

---

.circleci/build-image
.circleci/config.yml
buildfarm/base/Dockerfile
buildfarm/builder/Dockerfile
buildfarm/server/Dockerfile
buildfarm/worker/Dockerfile

Also, remove the explicit versions for installing apt-get packages. Also,
removed explicit versions for buildfarm images. Versioning these is not
useful, I just did that because of a linter, and while the linter is
right in most cases, these are images we build ourselves, and "latest" is
the only thing we care about here. The images should really not change
much over time anyway, so they shouldn't become incompatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/33)

Install docker before trying to give it credentials.

---

kythe/buildenv/build_index.sh

GHC needs tinfo, and the image doesn't have that yet. Also, building
haskell stuff has no use in kythe because we don't have a haskell
indexer yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/43)

fix: Disable haskell builds in kythe indexing.

---

.circleci/config.yml
freebsd/.nocache
freebsd/.nopush
freebsd/Dockerfile
freebsd/Makefile
freebsd/final/Dockerfile
freebsd/src/cmake-freebsd-env.sh
freebsd/src/cmake-freebsd-run.sh
freebsd/src/download-freebsd
freebsd/src/setup-vm
freebsd/src/setup-vm.expect

If it's not up after that, it won't come up. GitHub actions time out
after 6 hours. We can run out of runners when all of them are stuck
waiting for FreeBSD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/55)

fix: Put a time limit of 5 minutes for the VM to boot.

---

kythe/tables/Dockerfile

This reduces the size from 5GB to a few hundred MB, at the cost of not
having a cache, ever. That's ok though, because toktok-stack is
frequently updated, so the cache would be in the way anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/65)

perf: Only push final Kythe tables to the kythe-tables image.

---

buildfarm/builder/Dockerfile
kythe/buildenv/Dockerfile

It no longer needs to install extra dependencies. The bazel image already
does this now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/70)

chore: Clean up kythe buildenv.

---

buildfarm/bazel/Dockerfile

This allows us to run tests under valgrind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/72)

feat: Make valgrind available in the bazel base image.

---

buildfarm/bazel/Dockerfile

sudo will be used to allow the builder user to run root commands when
needed. gdb and strace can be used to debug binaries directly in the
container. ssh is needed for git to clone repos via ssh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/76)

chore: Add sudo, gdb, ssh, and strace to the bazel image.

---

kythe/buildenv/Dockerfile
kythe/buildenv/build_index.sh

It's no longer needed as of
https://github.com/TokTok/toktok-stack/pull/337.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/79)

chore: Remove android stuff from kythe buildenv.

---

flutter/web/Dockerfile

This happens because the version is worked out from the git tags in the
cloned repo.
This causes issues in e.g. dependency resolution as some libraries specify supported Flutter SDK versions.
```
#30 12.27 Running "flutter pub get" in app...
#30 14.53 The current Flutter SDK version is 0.0.0-unknown.
#30 14.53
#30 14.53 Because btox depends on sqlite3_flutter_libs >=0.1.0 which requires Flutter SDK version >=1.10.1, version solving failed.
#30 14.58 pub get failed (1; Because btox depends on sqlite3_flutter_libs >=0.1.0 which requires Flutter SDK version >=1.10.1, version solving failed.)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/dockerfiles/88)

fix: Fix Flutter SDK version being assumed to be 0.0.0-unknown

---

buildfarm/base/Dockerfile
kythe/webui/Dockerfile

Also update debian to latest stable. `stretch` is actually gone now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/103)

chore: Update to required bazel versions for buildfarm and kythe.

---

kythe/release/Dockerfile

Rust requires 800MB of rust toolchain, which exceeds the github actions disk space.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/110)

chore: Disable rust and typescript kythe extractors.

---

flutter/web/Dockerfile

Without this, there are random UID/GIDs without assigned user/group, which confuses non-root docker daemons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/111)

fix: chown flutter sdk to root:root.

---

flutter/web/Dockerfile

Not needed, as channel change already does it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/112)

cleanup: Remove useless flutter upgrade command

---

alpine-s390x/src/setup-vm.expect
freebsd/src/setup-vm

We needed it from iphydf for bootstrapping (CI). Now we can use it from master, because it's available now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/132)

cleanup: Use the master id_rsa.pub.

---

alpine-s390x/src/setup-vm.expect

Avoids having to do this in the toxcore CI build. Saves about half a minute in the s390x build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/133)

chore(deps): Preinstall more toxcore dependencies in the s390x image.

---

buildfarm/bazel/Dockerfile
buildfarm/bazel/arion-compose.nix
buildfarm/bazel/arion-pkgs.nix

Primary change is that now the activation script no longer sets up suid/sgid wrappers, and that functionality now moved to a systemd service, which we need to run manually in the docker build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/141)

chore: Upgrade nixos to 23.11.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.alpine

We don't need multiple tags per image, so we just use tags to differentiate them, like we do in toktok-stack.
Also added an alpine image build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/162)

chore: Rename qtox images to all be in the same dockerhub repo.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.android-builder

Hopefully we can see something more interesting in stack traces.
See https://github.com/TokTok/qTox/issues/172.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/174)

chore: Build the debug version of Qt for Android.

---

qtox/docker/Dockerfile.fedora

On Fedora, we build in Debug mode, which requires the ubsan runtime library so it can output nice error messages in tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/176)

chore: Add ubsan runtime library to fedora build.

---

qtox/docker/Dockerfile.alpine
qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.archlinux
qtox/docker/Dockerfile.debian
qtox/docker/Dockerfile.fedora
qtox/docker/Dockerfile.flatpak-builder
qtox/docker/Dockerfile.host-qt
qtox/docker/Dockerfile.ubuntu-lts
qtox/docker/Dockerfile.windows-builder

This won't do anything useful until we also set up ccache caching in the qtox workflows, but it's required to make that work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/179)

chore: Add ccache to qtox builder images.

---

qtox/docker/Dockerfile.windows-builder

Bootstrap node updater was broken before this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/181)

chore: Add missing tls plugins for qTox windows build.

---

qtox/docker/Dockerfile.windows-builder

We install both, and WINEARCH selects between them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/184)

fix: Add wine32 and wine64 to the qtox windows docker images.

---

qtox/docker/Dockerfile.alpine-static

Apparently it's not needed for bootstrapping Qt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/188)

cleanup: Don't install qttools unnecessarily.

---

qtox/build_qt_macos.sh

No ubsan runtime, just crash the program (with brk or int 3 or some other trap mechanism) when undefined behaviour is detected.
This should protect us against some classes of abusable bugs in Qt. Given there is no extra runtime, this will not increase the attack surface other than potentially DoSing users if crashing bugs are discovered. Still better than RCE-type abuse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/192)

chore: Build macOS static Qt with ubsan.

---

qtox/build_sodium.sh

Statically linked Qt contains the same symbols for its cryptographic hash implementation. They are deduped, but it's better to keep the 2 of them around for the libraries that use them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/194)

fix: Rename blake2b symbols in libsodium to avoid conflict with Qt.

---

qtox/build_ffmpeg.sh
qtox/build_openal.sh
qtox/download/download_openal.sh

We only need the ancient version on Windows because of loopback. On macOS, that ancient version doesn't work anymore because it uses long gone ancient macOS APIs (Apple doesn't believe in backwards compatibility, so those APIs simply don't work anymore).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/195)

chore: Use latest OpenAL on macOS.

---

qtox/docker/Dockerfile.alpine

This one doesn't build release binaries, so we can use it to see if qtox can still compile against a really old toxcore. 0.2.12 is from 2020.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/198)

chore: Use an ancient toxcore in qtox alpine build.

---

qtox/docker/Dockerfile.flatpak-builder
qtox/download/download_sodium.sh

Removed the downloads as well, because now we want to get them from within the manifest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/199)

chore: Update flatpak KDE SDK version to 6.8.

---

qtox/build_qt_macos.sh
qtox/build_qt_windows.sh
qtox/docker/Dockerfile.alpine-static

We don't need it. QtWidgets is not hardware accelerated. OpenGL support is only needed if we do OpenGL stuff ourselves.
Also disabled ubsan again. Qt isn't ubsan-clean.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/196)

cleanup: Build Qt without OpenGL support.

---

qtox/clang-pc-fixer
qtox/download/download_sodium.sh
qtox/download/download_sqlcipher.sh
qtox/download/download_toxcore.sh

We're not linking against libGL anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/203)

chore: Fix static qtox build.

---

qtox/docker/Dockerfile.android-builder
qtox/docker/Dockerfile.host-qt

We don't need it, but the Android builder image wants it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/213)

chore: Add back qmake to host-qt image.

---

qtox/build_extra_cmake_modules.sh
qtox/build_qtbase_linux.sh
qtox/build_qtimageformats_linux.sh
qtox/build_qtsvg_linux.sh
qtox/build_qttools_linux.sh
qtox/build_qtwayland_linux.sh
qtox/build_sonnet.sh
qtox/build_toxcore_linux.sh
qtox/build_utils.sh
qtox/docker/Dockerfile.alpine-appimage
qtox/download/download_qtbase.sh
qtox/download/download_qtimageformats.sh
qtox/download/download_qtsvg.sh
qtox/download/download_qttools.sh
qtox/download/download_qtwayland.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/217)

chore: Build our own Qt 6.8.1 in the appimage build.

---

qtox/docker/Dockerfile.alpine

We need Tox_File_Kind (which used to be TOX_FILE_KIND).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/221)

chore: Upgrade minimum toxcore version to 0.2.14.

---

qtox/docker/Dockerfile.flatpak-builder

https://discourse.flathub.org/t/running-gnome-builder-generated-project-from-command-line/7740/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/224)

chore: Upgrade to kde platform 6.8 in flatpak.

---

qtox/build_toxcore.sh

If a local version of c-toxcore is located in the place toktok-stack puts it, then use that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/223)

chore: Make local development a bit easier against toxcore.

---

qtox/build_qtimageformats_linux.sh
qtox/docker/Dockerfile.alpine-appimage

Builds fail if we delete some.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/231)

fix: Copy all the Qt imageformats, but not all kimageformats.

---

qtox/build_opus.sh
qtox/build_sodium.sh
qtox/build_utils.sh
qtox/build_vpx.sh

Also add support for iOS and arm64 Linux.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/238)

chore: Build libsodium with -fPIC for relocatable symbols.

---

.github/workflows/docker.yml
qtox/docker/Dockerfile.wasm-builder
qtox/docker/Dockerfile.windows-builder

So we can download it somewhere that doesn't support docker and use it there to build qtox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/244)

feat: Add a deploy build for the wasm toolchain.

---

qtox/build_toxcore.sh

We enable it on qt but no other dependencies at the moment (we probably should). This fixes it at least for toxcore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/246)

fix: Enable sanitizer on toxcore when requested.

---

qtox/download/download_tcl.sh

We don't use it, but this way we can control the TCL version in the flatpak descriptor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/dockerfiles/253)

chore: Add tcl download file for qtox.
